version: '3.6'
services:
  flask:
    build: 
      context: .
      dockerfile: "Flask/Dockerfile"
    ports:
      - "2000:5000"
    expose:
      - "2000"
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./main.py
    volumes:
      - "./Flask/:/app"
  node:
    build:
      context: .
      dockerfile: "Node/Dockerfile"
    command: "npm start"
    ports: 
      - "3000:80"
    expose:
      - "3000"
    volumes:
      - "./Node/:/var/www/app"